package cn.tyut.blog.dao;

import cn.tyut.blog.pojo.TArticleReview;
import org.springframework.stereotype.Repository;

@Repository
public interface TArticleReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_review
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    int deleteByPrimaryKey(Integer articleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_review
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    int insert(TArticleReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_review
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    int insertSelective(TArticleReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_review
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    TArticleReview selectByPrimaryKey(Integer articleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_review
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    int updateByPrimaryKeySelective(TArticleReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_review
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    int updateByPrimaryKey(TArticleReview record);
}