package cn.tyut.blog.dao;

import cn.tyut.blog.pojo.TArticleTagKey;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int deleteByPrimaryKey(TArticleTagKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int insert(TArticleTagKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article_tag
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int insertSelective(TArticleTagKey record);

    int connectionTags(@Param("articleId") int articleId,@Param("tagId") int tagId);

    String getTagNameByArticleId(@Param("articleId") int articleId);
}