package cn.tyut.blog.dao;

import cn.tyut.blog.pojo.TComment;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int deleteByPrimaryKey(Integer commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int insert(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int insertSelective(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    TComment selectByPrimaryKey(Integer commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int updateByPrimaryKeySelective(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int updateByPrimaryKey(TComment record);

    List<TComment> selectCommentListByArticleId(Integer articleid);

    int getCommentNum(Integer articleid);
}