package cn.tyut.blog.dao;

import cn.tyut.blog.pojo.TFileInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface TFileInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_info
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int deleteByPrimaryKey(Integer fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_info
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int insert(TFileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_info
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int insertSelective(TFileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_info
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    TFileInfo selectByPrimaryKey(Integer fileid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_info
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int updateByPrimaryKeySelective(TFileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_info
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int updateByPrimaryKey(TFileInfo record);
}