package cn.tyut.blog.dao;

import cn.tyut.blog.pojo.TFollow;
import org.springframework.stereotype.Repository;

@Repository
public interface TFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int deleteByPrimaryKey(Integer followid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int insert(TFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int insertSelective(TFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    TFollow selectByPrimaryKey(Integer followid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int updateByPrimaryKeySelective(TFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_follow
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    int updateByPrimaryKey(TFollow record);
}