package cn.tyut.blog.dao;

import cn.tyut.blog.pojo.TUserInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    int insert(TUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    int insertSelective(TUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    TUserInfo selectByPrimaryKey(Integer userid);

    int selectUser(@Param("userEmail") String userEmail, @Param("password") String password);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    int updateByPrimaryKeySelective(TUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_info
     *
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    int updateByPrimaryKey(TUserInfo record);

    int getUserId(@Param("userEmail")String userEmail);

    String getUserNameById(Integer userid);

    TUserInfo selecrUserByUserEmail(@Param("userEmail")String userEmail);
}