package cn.tyut.blog.dao;

import cn.tyut.blog.pojo.TUserIp;
import org.springframework.stereotype.Repository;

@Repository
public interface TUserIpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ip
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ip
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    int insert(TUserIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ip
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    int insertSelective(TUserIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ip
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    TUserIp selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ip
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    int updateByPrimaryKeySelective(TUserIp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_ip
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    int updateByPrimaryKey(TUserIp record);
}