package cn.tyut.blog.pojo;

public class TArticleReview {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_review.articleId
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    private Integer articleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_review.status
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_review.reason
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    private String reason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_review.articleId
     *
     * @return the value of t_article_review.articleId
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_review.articleId
     *
     * @param articleid the value for t_article_review.articleId
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_review.status
     *
     * @return the value of t_article_review.status
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_review.status
     *
     * @param status the value for t_article_review.status
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_review.reason
     *
     * @return the value of t_article_review.reason
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_review.reason
     *
     * @param reason the value for t_article_review.reason
     *
     * @mbggenerated Wed Apr 11 17:39:04 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason;
    }
}