package cn.tyut.blog.pojo;

public class TArticleTagKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_tag.articleId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private Integer articleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article_tag.tagId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private Integer tagid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_tag.articleId
     *
     * @return the value of t_article_tag.articleId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_tag.articleId
     *
     * @param articleid the value for t_article_tag.articleId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article_tag.tagId
     *
     * @return the value of t_article_tag.tagId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Integer getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article_tag.tagId
     *
     * @param tagid the value for t_article_tag.tagId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }
}