package cn.tyut.blog.pojo;

public class TComment {

    private Integer commentid;

    private Integer userid;

    private Integer articleid;

    private String content;

    private Long createtime;

    private Integer recommentid;

    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.commentId
     *
     * @param commentid the value for t_comment.commentId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.userId
     *
     * @return the value of t_comment.userId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.userId
     *
     * @param userid the value for t_comment.userId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.articleId
     *
     * @return the value of t_comment.articleId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.articleId
     *
     * @param articleid the value for t_comment.articleId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.content
     *
     * @return the value of t_comment.content
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.content
     *
     * @param content the value for t_comment.content
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.createTime
     *
     * @return the value of t_comment.createTime
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.createTime
     *
     * @param createtime the value for t_comment.createTime
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.reCommentId
     *
     * @return the value of t_comment.reCommentId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Integer getRecommentid() {
        return recommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.reCommentId
     *
     * @param recommentid the value for t_comment.reCommentId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setRecommentid(Integer recommentid) {
        this.recommentid = recommentid;
    }
}