package cn.tyut.blog.pojo;

public class TFileInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_info.fileId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private Integer fileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_info.fileName
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_info.uri
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private String uri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_info.createTime
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file_info.type
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_info.fileId
     *
     * @return the value of t_file_info.fileId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_info.fileId
     *
     * @param fileid the value for t_file_info.fileId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_info.fileName
     *
     * @return the value of t_file_info.fileName
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_info.fileName
     *
     * @param filename the value for t_file_info.fileName
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_info.uri
     *
     * @return the value of t_file_info.uri
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_info.uri
     *
     * @param uri the value for t_file_info.uri
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setUri(String uri) {
        this.uri = uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_info.createTime
     *
     * @return the value of t_file_info.createTime
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_info.createTime
     *
     * @param createtime the value for t_file_info.createTime
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file_info.type
     *
     * @return the value of t_file_info.type
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file_info.type
     *
     * @param type the value for t_file_info.type
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }
}