package cn.tyut.blog.pojo;

public class TFollow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.followId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private Integer followid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.userId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_follow.followerId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private Integer followerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.followId
     *
     * @return the value of t_follow.followId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Integer getFollowid() {
        return followid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.followId
     *
     * @param followid the value for t_follow.followId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setFollowid(Integer followid) {
        this.followid = followid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.userId
     *
     * @return the value of t_follow.userId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.userId
     *
     * @param userid the value for t_follow.userId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_follow.followerId
     *
     * @return the value of t_follow.followerId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Integer getFollowerid() {
        return followerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_follow.followerId
     *
     * @param followerid the value for t_follow.followerId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setFollowerid(Integer followerid) {
        this.followerid = followerid;
    }
}