package cn.tyut.blog.pojo;

public class TTags {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tags.tagId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private Integer tagid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tags.tagName
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private String tagname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tags.createTime
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_tags.updateTime
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    private Long updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tags.tagId
     *
     * @return the value of t_tags.tagId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Integer getTagid() {
        return tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tags.tagId
     *
     * @param tagid the value for t_tags.tagId
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setTagid(Integer tagid) {
        this.tagid = tagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tags.tagName
     *
     * @return the value of t_tags.tagName
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public String getTagname() {
        return tagname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tags.tagName
     *
     * @param tagname the value for t_tags.tagName
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setTagname(String tagname) {
        this.tagname = tagname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tags.createTime
     *
     * @return the value of t_tags.createTime
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tags.createTime
     *
     * @param createtime the value for t_tags.createTime
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_tags.updateTime
     *
     * @return the value of t_tags.updateTime
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public Long getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_tags.updateTime
     *
     * @param updatetime the value for t_tags.updateTime
     *
     * @mbggenerated Mon Mar 26 14:01:12 CST 2018
     */
    public void setUpdatetime(Long updatetime) {
        this.updatetime = updatetime;
    }
}