package cn.tyut.blog.pojo;

import org.springframework.stereotype.Repository;

@Repository
public class TUserInfo {

    private Integer userid;
    private String email;
    private String username;
    private String password;
    private Long phone;
    private String headpic;
    private Integer age;
    private String sex;
    private String introduce;
    private String profession;
    private String address;

    public TUserInfo() {
    }

    /**
     *
     * @param userid
     * @param email
     * @param username
     * @param password
     * @param phone
     * @param headpic
     * @param age
     * @param sex
     * @param introduce
     * @param profession
     * @param address
     */
    public TUserInfo(Integer userid, String email, String username, String password, Long phone, String headpic, Integer age, String sex, String introduce, String profession, String address) {
        this.userid = userid;
        this.email = email;
        this.username = username;
        this.password = password;
        this.phone = phone;
        this.headpic = headpic;
        this.age = age;
        this.sex = sex;
        this.introduce = introduce;
        this.profession = profession;
        this.address = address;
    }

    public Integer getUserid() {
        return userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.email
     *
     * @return the value of t_user_info.email
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.email
     *
     * @param email the value for t_user_info.email
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.userName
     *
     * @return the value of t_user_info.userName
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.userName
     *
     * @param username the value for t_user_info.userName
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.password
     *
     * @return the value of t_user_info.password
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.password
     *
     * @param password the value for t_user_info.password
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.phone
     *
     * @return the value of t_user_info.phone
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public Long getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.phone
     *
     * @param phone the value for t_user_info.phone
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public void setPhone(Long phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.headPic
     *
     * @return the value of t_user_info.headPic
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public String getHeadpic() {
        return headpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.headPic
     *
     * @param headpic the value for t_user_info.headPic
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public void setHeadpic(String headpic) {
        this.headpic = headpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.age
     *
     * @return the value of t_user_info.age
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.age
     *
     * @param age the value for t_user_info.age
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.sex
     *
     * @return the value of t_user_info.sex
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.sex
     *
     * @param sex the value for t_user_info.sex
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.Introduce
     *
     * @return the value of t_user_info.Introduce
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.Introduce
     *
     * @param introduce the value for t_user_info.Introduce
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.profession
     *
     * @return the value of t_user_info.profession
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.profession
     *
     * @param profession the value for t_user_info.profession
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public void setProfession(String profession) {
        this.profession = profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_info.address
     *
     * @return the value of t_user_info.address
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_info.address
     *
     * @param address the value for t_user_info.address
     * @mbggenerated Fri May 04 14:08:02 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }


    @Override
    public String toString() {
        return "TUserInfo{" +
                "userid=" + userid +
                ", email='" + email + '\'' +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", phone=" + phone +
                ", headpic='" + headpic + '\'' +
                ", age=" + age +
                ", sex='" + sex + '\'' +
                ", introduce='" + introduce + '\'' +
                ", profession='" + profession + '\'' +
                ", address='" + address + '\'' +
                '}';
    }
}